### PR TITLE
add allow flip flag

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by geneotech** [comment]
I've tested both options in my game, looks like it works! Thank you!

**Comment by Longri** [comment]
Do you want to merge the branch into the master?

I wanted to submit another PR to extend the' struct rect_xywhf' with an index.
This gives you the possibility to identify the rect's and draw them later!

**Comment by geneotech** [comment]
``Longri:add_allow_flip_flag`` branch is already merged into ``TeamHypersomnia:master``.

Thanks for the suggestion, but as of currently, I don't see a need to index the rectangles - the algorithm does not at all rearrange them, because it only acquires a vector of pointers to inputs. The bins contain pointers as well, so if we're iterating bin-wise, these can too be used for identification.

**Comment by geneotech** [comment]
On the other hand, if I were to write the algorithm again, I would probably use templates in the first place and make it a header-only library where you can plug-in your own types. I'm scared to modify it after all these years, though! 😅

**Comment by Longri** [comment]
Indexing the rectangles I need to get back to Java, because the drawing is done on Java level.

From Java I call this native function by passing an int[];

```
        valueArray[idx++] pixmap.getIndex(); // index
        valueArray[idx++] =  // x
        valueArray[idx++] = // y
        valueArray[idx++] = // width
        valueArray[idx++] =  // height
        valueArray[idx++] = // flipped
        valueArray[idx++] =  // textureIndex (bin number)
```




> On the other hand, if I were to write the algorithm again, I would probably use templates in the first place and make it a header-only library where you can plug-in your own types. I'm scared to modify it after all these years, though!

Don't touch running sysytems!
And your  lib is smal, fast and efficient!

**Pull request merged**
